services:
  eurekaserver:
    image: clay404/eurekaserver:v1
    container_name: eurekaserver
    ports:
      - "8070:8070"
    deploy:
      resources:
        limits:
          memory: 700m
    healthcheck:
      test: "curl --fail --silent localhost:8070/actuator/health/readiness | grep UP || exit 1"
      interval: 20s
      timeout: 5s
      retries: 20
      start_period: 10s
    extends:
      file: common-config.yaml
      service: microservice-base-config
    environment:
      SPRING_APPLICATION_NAME: "eurekaserver"

  angulargenerator:
    image: clay404/angulargenerator:v1
    container_name: angulargenerator
    ports:
      - "9081:9081"
    extends:
      file: common-config.yaml
      service: microservice-eurekaserver-config
    environment:
      SPRING_APPLICATION_NAME: "angulargenerator"
networks:
  archworker:
    driver: "bridge"