spring:
  cloud:
    gateway:
      routes:
        - id: angulargenerator
          uri: lb://ANGULARGENERATOR
          predicates:
            - Path=/arch/angulargenerator/**
          filters:
            - RewritePath=/arch/angulargenerator/(?<segment>.*), /${segment}
            - name: CircuitBreaker
              args:
                name: angulargeneratorCircuitBreaker
                fallbackUri: forward:/contact-support
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 3  # Number of requests per second
                redis-rate-limiter.burstCapacity: 2  # Maximum number of requests allowed in a burst
                key-resolver: '#{@userKeyResolver}'   # Bean reference for resolving keys
