FROM openjdk:17-jdk-slim

MAINTAINER shahbytes.com

COPY target/angulargenerator-0.0.1-SNAPSHOT.jar angulargenerator-0.0.1-SNAPSHOT.jar

ENTRYPOINT ["java","-jar","angulargenerator-0.0.1-SNAPSHOT.jar"]